### ISSUE TITLE
Suggestions!!!

### ISSUE THREAD

**Issue by gsrathoreniks** [bipuldevashish/Trader#5]
- [ ] Migrate the project to KOTLIN
**WHY**
Because if you want to mention Android Developer in your profile, recruiters always ask if you've experience with Kotlin or not. Since it's easy and better. Let's get started...
Will help you if needed.

- [x] We know how to make apps, It's time to write better code which can be maintained, understood, tested scaled easily.

**Comment by gsrathoreniks** [comment]
@SingAvi

**Comment by SingAvi** [comment]
Bipul needs time to shift to kotlin and he has promised to deliver app on time,

**Comment by gsrathoreniks** [comment]
Is it a freelance project?

**Comment by SingAvi** [comment]
No Details yet, Bipul might tell me by morning

**Comment by gsrathoreniks** [comment]
No worries,

Will study the code time-to-time and will update you if something[small] can be done better.

**Comment by gsrathoreniks** [comment]
@SingAvi 
Please check the APPLICATION ID
> com.example.bipuldevashish

It's not professional and should be changed acc. to client's need.
